version: '3.4'

networks:
   dockerapi-dev:
      driver: bridge

services:
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - dockerapi-dev

  vacation_calendar_api:
    image: ${DOCKER_REGISTRY-}vacation-calendar-api
    build:
      context: .
      dockerfile: VacationCalendar.Api/Dockerfile
    ports:
      - "4015:443"
    networks:
      - dockerapi-dev

volumes:
  db_volume:

