version: '3.4'

networks:
   dockerapi-dev:
      driver: bridge

services:
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - dockerapi-dev
    profiles:
      [backend]

  vacation_calendar_api:
    image: ${DOCKER_REGISTRY-}vacation_calendar_api
    build:
      context: .
      dockerfile: VacationCalendar.Api/Dockerfile
    ports:
      - "4015:443"
    depends_on:
      - postgres_image
    networks:
      - dockerapi-dev
    profiles:
      [backend]

  vacation_calendar_angular:
    image: ${DOCKER_REGISTRY-}vacation_calendar_angular
    build:
      context: ./VacationCalendarAngular
      dockerfile: Dockerfile
    networks:
      - dockerapi-dev
    profiles:
      [frontend]
    ports:
      - '4014:80'

volumes:
  db_volume: